// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCMw8VUOOf9aAlEhmxs39wrLODWQZ3J8',
    appId: '1:702335281599:web:2901ff660837dbbdc6990a',
    messagingSenderId: '702335281599',
    projectId: 'aquatrack-pro-a4e09',
    authDomain: 'aquatrack-pro-a4e09.firebaseapp.com',
    databaseURL: 'https://aquatrack-pro-a4e09-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aquatrack-pro-a4e09.firebasestorage.app',
    measurementId: 'G-EDW3Z48QWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ869J_Uq00FyAKp2BFb3XmeiTeMQIzJc',
    appId: '1:702335281599:android:bb8f07e481be88adc6990a',
    messagingSenderId: '702335281599',
    projectId: 'aquatrack-pro-a4e09',
    databaseURL: 'https://aquatrack-pro-a4e09-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aquatrack-pro-a4e09.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRk1N6TvG6gwbhx9WAlcMtspQ6l_KX58',
    appId: '1:702335281599:ios:31127f761350a480c6990a',
    messagingSenderId: '702335281599',
    projectId: 'aquatrack-pro-a4e09',
    databaseURL: 'https://aquatrack-pro-a4e09-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aquatrack-pro-a4e09.firebasestorage.app',
    iosClientId: '702335281599-ur83l2kgdt17he7m564t0fgnhd0u7uja.apps.googleusercontent.com',
    iosBundleId: 'com.aquatrack.pro.aquatrackPro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRk1N6TvG6gwbhx9WAlcMtspQ6l_KX58',
    appId: '1:702335281599:ios:31127f761350a480c6990a',
    messagingSenderId: '702335281599',
    projectId: 'aquatrack-pro-a4e09',
    databaseURL: 'https://aquatrack-pro-a4e09-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aquatrack-pro-a4e09.firebasestorage.app',
    iosClientId: '702335281599-ur83l2kgdt17he7m564t0fgnhd0u7uja.apps.googleusercontent.com',
    iosBundleId: 'com.aquatrack.pro.aquatrackPro',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYH2d5wMf3eZXID-ZBSl554CB2Fzlqib0',
    appId: '1:326972943372:web:2a83b88c7d63930a8cd229',
    messagingSenderId: '326972943372',
    projectId: 'aquatrack-pro-ba384',
    authDomain: 'aquatrack-pro-ba384.firebaseapp.com',
    databaseURL: 'https://aquatrack-pro-ba384-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aquatrack-pro-ba384.firebasestorage.app',
  );
}
