import 'package:flutter/material.dart';

class AppLocalizations {
  Locale locale;

  AppLocalizations(this.locale);

  bool get isArabic => locale.languageCode == 'ar';
  TextDirection get textDirection => isArabic ? TextDirection.rtl : TextDirection.ltr;

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_name': 'أكواتراك برو',
      'app_subtitle': 'منصة متابعة السباحين الناشئين',
      'welcome': 'مرحباً بك',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'full_name': 'الاسم الكامل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'or_continue_with': 'أو تابع باستخدام',
      'google_sign_in': 'Google',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'create_account': 'إنشاء حساب جديد',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'loading': 'جاري التحميل...',
      'error': 'حدث خطأ',
      'success': 'تم بنجاح',
      'retry': 'إعادة المحاولة',
      'confirm': 'تأكيد',
      'skip': 'تخطي',
      'next': 'التالي',
      'done': 'تم',
      'search': 'بحث',
      'no_data': 'لا توجد بيانات',
      'offline_mode': 'وضع عدم الاتصال',
      'sync_now': 'مزامنة الآن',

      // Athlete
      'add_athlete': 'إضافة متدرب',
      'edit_athlete': 'تعديل بيانات المتدرب',
      'athlete_name': 'اسم المتدرب',
      'birth_date': 'تاريخ الميلاد',
      'age': 'العمر',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'swim_level': 'مستوى السباحة',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'competitive': 'تنافسي',
      'weight': 'الوزن (كجم)',
      'height': 'الطول (سم)',
      'weekly_goal': 'الهدف الأسبوعي (ساعات)',
      'athlete_photo': 'صورة المتدرب',
      'not_logged_today': 'لم يُسجَّل اليوم',
      'logged_today': 'تم التسجيل اليوم',

      // Daily Log
      'daily_log': 'التسجيل اليومي',
      'step': 'خطوة',
      'of': 'من',
      'resting_hr_title': 'ما نبض @name صباح اليوم؟',
      'resting_hr_subtitle': 'القياس عند الاستيقاظ مباشرة قبل القيام',
      'resting_hr_hint': 'نبض الراحة (BPM)',
      'normal_range': 'النطاق الطبيعي لعمر @age: @min-@max BPM',
      'sleep_title': 'كيف نام @name؟',
      'sleep_hours': 'ساعات النوم',
      'sleep_quality': 'جودة النوم',
      'poor': 'ضعيف',
      'fair': 'عادي',
      'good': 'جيد',
      'low_sleep_warning': 'تنبيه: @name ينام أقل من الموصى به (@recommended ساعات)',
      'wellness_title': 'كيف يشعر @name الصباح؟',
      'wellness_1': 'متعب جداً',
      'wellness_2': 'متعب',
      'wellness_3': 'عادي',
      'wellness_4': 'جيد',
      'wellness_5': 'ممتاز',
      'nutrition_title': 'ماذا أكل @name اليوم؟',
      'breakfast': 'فطور',
      'lunch': 'غداء',
      'dinner': 'عشاء',
      'snack': 'وجبة خفيفة',
      'water_intake': 'كمية الماء (لتر)',
      'protein_sufficient': 'تناول بروتين كافٍ؟',
      'training_title': 'هل تدرّب @name اليوم؟',
      'trained_yes': 'تدرّب',
      'trained_no': 'لم يتدرب',
      'training_type': 'نوع التدريب',
      'technique': 'تقنية',
      'endurance': 'تحمّل',
      'sprint': 'سرعة',
      'dryland': 'جاف',
      'competition': 'منافسة',
      'rest': 'راحة',
      'duration': 'المدة (دقيقة)',
      'distance': 'المسافة (متر)',
      'rpe': 'معدل الجهد (RPE)',
      'rpe_very_light': 'خفيف جداً',
      'rpe_light': 'خفيف',
      'rpe_moderate': 'متوسط',
      'rpe_hard': 'شاق',
      'rpe_very_hard': 'أقصى جهد',
      'log_success': 'تم تسجيل اليوم بنجاح!',
      'log_edit_success': 'تم تعديل التسجيل بنجاح!',
      'existing_log_warning': 'يوجد تسجيل سابق لليوم — سيتم التعديل',
      'previous': 'السابق',
      'step_rhr_label': 'النبض',
      'step_sleep_label': 'النوم',
      'step_wellness_label': 'النشاط',
      'step_nutrition_label': 'التغذية',
      'step_training_label': 'التدريب',
      'hours': 'ساعة',
      'sleep_recommendation': 'الموصى به: @min-@max ساعة لعمر @age سنة',
      'wellness_subtitle': 'تقييم الحالة العامة للرياضي عند الاستيقاظ',
      'wellness_detail_1': 'متعب جداً — إرهاق واضح',
      'wellness_detail_2': 'متعب — أقل من المعتاد',
      'wellness_detail_3': 'عادي — مقبول',
      'wellness_detail_4': 'جيد — حالة جيدة',
      'wellness_detail_5': 'ممتاز — نشاط وحيوية',
      'wellness_skip_hint': '(يمكنك تخطي هذه الخطوة)',
      'liters': 'لتر',
      'protein_question': '🍗 تناول بروتين كافٍ اليوم؟',
      'yes_label': 'نعم ✅',
      'no_label': 'لا',
      'meals': 'الوجبات',
      'hydration': 'الماء',
      'protein': 'البروتين',
      'discard_title': 'تجاهل التقدم؟',
      'discard_body': 'سيتم فقدان البيانات المدخلة. هل أنت متأكد؟',
      'discard_confirm': 'تجاهل',
      'keep_editing': 'مواصلة التعديل',
      'meals_completed': 'الوجبات المكتملة',
      'meals_count': '@count من 4 وجبات',
      'training_duration': 'مدة التدريب',
      'minutes': 'دقيقة',
      'distance_hint': 'المسافة (متر) — اختياري',
      'm_suffix': 'م',

      // Dashboard
      'dashboard': 'الرئيسية',
      'today_status': 'حالة @name — @date',
      'last_updated': 'آخر تحديث',
      'stress_score': 'مؤشر الإجهاد',
      'excellent': 'ممتاز',
      'normal': 'طبيعي',
      'warning': 'تحذير',
      'danger': 'خطر',
      'sleep': 'النوم',
      'heart_rate': 'النبض',
      'nutrition': 'التغذية',
      'training': 'التدريب',
      'weekly_wellness': 'مؤشرات 7 أيام',
      'alerts': 'التنبيهات',
      'no_alerts': 'لا توجد تنبيهات',
      'log_today': 'سجّل اليوم',
      'edit_log': 'عدّل التسجيل',
      'compared_to_yesterday': 'عن الأمس',
      'compare_to_recommended': 'مقارنة بالموصى به',
      'weekly_trend': 'اتجاه 7 أيام',
      'today_session': 'جلسة اليوم',
      'weekly_total': 'إجمالي الأسبوع',

      // AI
      'ai_assistant': 'المساعد الذكي',
      'ask_question': 'اسأل المساعد الذكي',
      'type_question': 'اكتب سؤالك...',
      'ai_context': 'بيانات @name — نوم @sleep | نبض @hr | ACWR @acwr',
      'ai_suggestions': 'أسئلة مقترحة',
      'ai_suggestion_1': 'ماذا يأكل @name قبل التدريب؟',
      'ai_suggestion_2': 'هل نومه هذا الأسبوع كافٍ؟',
      'ai_suggestion_3': 'كيف أقلل نبضه الصباحي المرتفع؟',
      'citation': 'المصدر',
      'confidence_high': 'عالية',
      'confidence_medium': 'متوسطة',
      'confidence_low': 'منخفضة',
      'medical_disclaimer': 'هذه الإجابة لأغراض تعليمية وليست بديلاً عن الاستشارة الطبية',
      'messages_remaining': '@count رسالة متبقية اليوم',
      'pro_unlimited': 'غير محدود (Pro)',

      // Reports
      'reports': 'التقارير',
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'strengths': 'نقاط القوة',
      'improvements': 'نقاط التحسين',
      'export_pdf': 'تصدير PDF',
      'share': 'مشاركة',
      'sleep_compliance': 'الامتثال للنوم',
      'training_load': 'حجم التدريب',
      'nutrition_radar': 'التغذية',
      'injury_timeline': 'الإصابات',
      'ai_summary': 'الملخص الذكي',

      // Settings
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'subscription': 'الباقة',
      'free': 'مجانية',
      'pro': 'احترافية',
      'notifications': 'الإشعارات',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'privacy': 'الخصوصية',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_of_service': 'شروط الخدمة',
      'export_data': 'صدّر بياناتي',
      'delete_account': 'احذف حسابي',
      'delete_confirm': 'هل أنت متأكد؟ هذا الإجراء لا يُرجع',
      'support': 'الدعم',
      'faq': 'الأسئلة الشائعة',
      'contact_us': 'تواصل معنا',
      'rate_app': 'تقييم التطبيق',
      'version': 'الإصدار',
      'about': 'حول التطبيق',
      'disclaimer': 'هذا التطبيق ليس بديلاً عن الاستشارة الطبية',
      'account_info': 'معلومات الحساب',
      'account_type': 'نوع الحساب',
      'athlete_count': 'عدد المتدربين',
      'enabled': 'مفعلة',
      'dark_mode': 'الوضع الليلي',
      'help': 'مساعدة',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_body': 'هل أنت متأكد من تسجيل الخروج؟',
      'logout_btn': 'تسجيل الخروج',
      'rate_now': 'تقييم الآن',
      'rate_question': 'هل أعجبك التطبيق؟',
      'rate_yes': 'نعم!',
      'rate_later': 'لاحقاً',
      'rate_already': 'شكراً لتقييمك! ❤️',
      'feedback_thanks': 'شكراً لملاحظاتك!',

      // Athletes Tab
      'athletes': 'المتدربون',
      'no_athletes_yet': 'لا يوجد متدربون بعد',
      'add_athlete_to_start': 'أضف متدرباً لبدء المتابعة',
      'view_profile': 'عرض الملف الشخصي',
      'edit_data': 'تعديل البيانات',
      'delete_athlete': 'حذف المتدرب',
      'confirm_delete_title': 'تأكيد الحذف',
      'confirm_delete_body': 'هل أنت متأكد من حذف "@name"؟ لا يمكن التراجع عن هذا الإجراء.',

      // Athlete Detail
      'baseline_measurements': 'القياسات الأساسية',
      'last_14_days': 'آخر 14 يوم',
      'no_logs_yet': 'لا توجد سجلات بعد',
      'log_first_day': 'تسجيل أول يوم',
      'recent_logs': 'آخر السجلات',
      'resting_hr_baseline': 'النبض الأساسي',
      'sleep_baseline': 'النوم الأساسي',

      // Add Athlete
      'basic_info': 'بيانات المتدرب الأساسية',
      'training_level': 'مستوى التدريب',
      'measurements_optional': 'القياسات (اختياري)',
      'save_changes': 'حفظ التغييرات',
      'choose_birth_date': 'يرجى اختيار تاريخ الميلاد',
      'select_date_hint': 'اختر التاريخ',

      // Dashboard
      'welcome_to_app': 'أهلاً بك في أكواتراك برو',
      'not_logged_yet': 'لم يُسجَّل اليوم بعد',
      'log_now': 'سجّل الآن',
      'last_updated_today': 'آخر تحديث: اليوم',
      'no_data_yet': 'لم يُسجّل',
      'rest_day': 'راحة',

      // Reports
      'add_athlete_first': 'أضف متدرباً أولاً',
      'no_data_enough': 'لا توجد بيانات كافية',
      'days_7': '7أ',
      'days_14': '14أ',
      'days_30': '30أ',
      'stress': 'الإجهاد',

      // General
      'coming_soon': 'قريباً',
      'years_old': 'سنة',
      'beats': 'نبضة',

      // COPPA
      'consent_title': 'موافقة ولي الأمر',
      'consent_text': 'أوافق على جمع وتخزين بيانات طفلي الصحية لغرض المتابعة والتحليل الرياضي. أفهم أن البيانات ستُستخدم فقط لهذا الغرض ولن تُشارك مع أطراف ثالثة.',
      'consent_agree': 'أوافق',
      'consent_disagree': 'لا أوافق',
      'parental_consent_required': 'موافقة ولي الأمر مطلوبة',
      'forgot_password_body': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور',
      'send_reset_link': 'إرسال رابط إعادة التعيين',
      'reset_email_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
      'and': 'و',
    },
    'en': {
      'app_name': 'AquaTrack Pro',
      'app_subtitle': 'Junior Swimmer Monitoring Platform',
      'welcome': 'Welcome',
      'login': 'Login',
      'register': 'Create Account',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'forgot_password': 'Forgot Password?',
      'or_continue_with': 'Or continue with',
      'google_sign_in': 'Google',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'create_account': 'Create New Account',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'confirm': 'Confirm',
      'skip': 'Skip',
      'next': 'Next',
      'done': 'Done',
      'search': 'Search',
      'no_data': 'No data',
      'offline_mode': 'Offline Mode',
      'sync_now': 'Sync Now',

      // Athlete
      'add_athlete': 'Add Athlete',
      'edit_athlete': 'Edit Athlete',
      'athlete_name': 'Athlete Name',
      'birth_date': 'Date of Birth',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'swim_level': 'Swim Level',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'competitive': 'Competitive',
      'weight': 'Weight (kg)',
      'height': 'Height (cm)',
      'weekly_goal': 'Weekly Goal (hours)',
      'athlete_photo': 'Athlete Photo',
      'not_logged_today': 'Not logged today',
      'logged_today': 'Logged today',

      // Daily Log
      'daily_log': 'Daily Log',
      'step': 'Step',
      'of': 'of',
      'resting_hr_title': "What is @name's morning resting HR?",
      'resting_hr_subtitle': 'Measure immediately upon waking, before getting up',
      'resting_hr_hint': 'Resting HR (BPM)',
      'normal_range': 'Normal range for age @age: @min-@max BPM',
      'sleep_title': "How did @name sleep?",
      'sleep_hours': 'Sleep Hours',
      'sleep_quality': 'Sleep Quality',
      'poor': 'Poor',
      'fair': 'Fair',
      'good': 'Good',
      'low_sleep_warning': 'Warning: @name sleeps less than recommended (@recommended hours)',
      'wellness_title': "How does @name feel this morning?",
      'wellness_1': 'Very Tired',
      'wellness_2': 'Tired',
      'wellness_3': 'Okay',
      'wellness_4': 'Good',
      'wellness_5': 'Excellent',
      'nutrition_title': "What did @name eat today?",
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snack': 'Snack',
      'water_intake': 'Water Intake (liters)',
      'protein_sufficient': 'Sufficient protein?',
      'training_title': "Did @name train today?",
      'trained_yes': 'Trained',
      'trained_no': 'Did not train',
      'training_type': 'Training Type',
      'technique': 'Technique',
      'endurance': 'Endurance',
      'sprint': 'Sprint',
      'dryland': 'Dryland',
      'competition': 'Competition',
      'rest': 'Rest',
      'duration': 'Duration (min)',
      'distance': 'Distance (m)',
      'rpe': 'Rate of Perceived Exertion',
      'rpe_very_light': 'Very Light',
      'rpe_light': 'Light',
      'rpe_moderate': 'Moderate',
      'rpe_hard': 'Hard',
      'rpe_very_hard': 'Max Effort',
      'log_success': 'Today\'s log saved successfully!',
      'log_edit_success': 'Log updated successfully!',
      'existing_log_warning': 'An existing log was found — editing in progress',
      'previous': 'Previous',
      'step_rhr_label': 'Pulse',
      'step_sleep_label': 'Sleep',
      'step_wellness_label': 'Wellness',
      'step_nutrition_label': 'Nutrition',
      'step_training_label': 'Training',
      'hours': 'hours',
      'sleep_recommendation': 'Recommended: @min-@max hours for age @age',
      'wellness_subtitle': 'Assess the athlete\'s general condition upon waking',
      'wellness_detail_1': 'Very Tired — Clear Fatigue',
      'wellness_detail_2': 'Tired — Less than usual',
      'wellness_detail_3': 'Okay — Acceptable',
      'wellness_detail_4': 'Good — Good condition',
      'wellness_detail_5': 'Excellent — Energetic',
      'wellness_skip_hint': '(You can skip this step)',
      'liters': 'L',
      'protein_question': '🍗 Sufficient protein today?',
      'yes_label': 'Yes ✅',
      'no_label': 'No',
      'meals': 'Meals',
      'hydration': 'Hydration',
      'protein': 'Protein',
      'discard_title': 'Discard Progress?',
      'discard_body': 'Entered data will be lost. Are you sure?',
      'discard_confirm': 'Discard',
      'keep_editing': 'Keep Editing',
      'meals_completed': 'Meals Completed',
      'meals_count': '@count of 4 meals',
      'training_duration': 'Training Duration',
      'minutes': 'min',
      'distance_hint': 'Distance (m) — optional',
      'm_suffix': 'm',

      // Dashboard
      'dashboard': 'Dashboard',
      'today_status': "@name's Status — @date",
      'last_updated': 'Last Updated',
      'stress_score': 'Stress Score',
      'excellent': 'Excellent',
      'normal': 'Normal',
      'warning': 'Warning',
      'danger': 'Danger',
      'sleep': 'Sleep',
      'heart_rate': 'Heart Rate',
      'nutrition': 'Nutrition',
      'training': 'Training',
      'weekly_wellness': '7-Day Wellness',
      'alerts': 'Alerts',
      'no_alerts': 'No alerts',
      'log_today': 'Log Today',
      'edit_log': 'Edit Today\'s Log',
      'compared_to_yesterday': 'vs yesterday',
      'compare_to_recommended': 'vs recommended',
      'weekly_trend': '7-Day Trend',
      'today_session': "Today's Session",
      'weekly_total': 'Weekly Total',

      // AI
      'ai_assistant': 'AI Coach',
      'ask_question': 'Ask the AI Coach',
      'type_question': 'Ask anything about training...',
      'ai_context': '@name — Sleep @sleep | HR @hr | ACWR @acwr',
      'ai_suggestions': 'Try asking:',
      'ai_suggestion_1': 'What should @name eat before practice?',
      'ai_suggestion_2': 'Is @name sleeping enough this week?',
      'ai_suggestion_3': 'How can I lower @name\'s morning HR?',
      'citation': 'Sources',
      'confidence_high': 'High',
      'confidence_medium': 'Medium',
      'confidence_low': 'Low',
      'medical_disclaimer': 'For educational purposes only — consult a healthcare professional',
      'messages_remaining': '@count messages remaining today',
      'pro_unlimited': 'Unlimited (Pro)',
      'ai_welcome': 'Hi! I\'m your AI Swim Coach. I\'ve analyzed @name\'s data and our training library. Ask me about training, nutrition, recovery, or anything about swimming!',

      // Reports
      'reports': 'Reports',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'strengths': 'Strengths',
      'improvements': 'Areas for Improvement',
      'export_pdf': 'Export PDF',
      'share': 'Share',
      'sleep_compliance': 'Sleep Compliance',
      'training_load': 'Training Load',
      'nutrition_radar': 'Nutrition',
      'injury_timeline': 'Injuries',
      'ai_summary': 'AI Summary',

      // Settings
      'settings': 'Settings',
      'profile': 'Profile',
      'subscription': 'Subscription',
      'free': 'Free',
      'pro': 'Pro',
      'notifications': 'Notifications',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'privacy': 'Privacy',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'export_data': 'Export My Data',
      'delete_account': 'Delete My Account',
      'delete_confirm': 'Are you sure? This action cannot be undone.',
      'support': 'Support',
      'faq': 'FAQ',
      'contact_us': 'Contact Us',
      'rate_app': 'Rate App',
      'version': 'Version',
      'about': 'About',
      'disclaimer': 'This app is not a substitute for medical advice',
      'account_info': 'Account Info',
      'account_type': 'Account Type',
      'athlete_count': 'Athlete Count',
      'enabled': 'Enabled',
      'dark_mode': 'Dark Mode',
      'help': 'Help',
      'logout_confirm_title': 'Logout',
      'logout_confirm_body': 'Are you sure you want to logout?',
      'logout_btn': 'Logout',
      'rate_now': 'Rate Now',
      'rate_question': 'Do you like the app?',
      'rate_yes': 'Yes!',
      'rate_later': 'Later',
      'rate_already': 'Thanks for rating! ❤️',
      'feedback_thanks': 'Thanks for your feedback!',

      // Athletes Tab
      'athletes': 'Athletes',
      'no_athletes_yet': 'No athletes yet',
      'add_athlete_to_start': 'Add an athlete to start monitoring',
      'view_profile': 'View Profile',
      'edit_data': 'Edit Data',
      'delete_athlete': 'Delete Athlete',
      'confirm_delete_title': 'Confirm Delete',
      'confirm_delete_body': 'Are you sure you want to delete "@name"? This action cannot be undone.',

      // Athlete Detail
      'baseline_measurements': 'Baseline Measurements',
      'last_14_days': 'Last 14 Days',
      'no_logs_yet': 'No logs yet',
      'log_first_day': 'Log First Day',
      'recent_logs': 'Recent Logs',
      'resting_hr_baseline': 'Resting HR Baseline',
      'sleep_baseline': 'Sleep Baseline',

      // Add Athlete
      'basic_info': 'Basic Info',
      'training_level': 'Training Level',
      'measurements_optional': 'Measurements (Optional)',
      'save_changes': 'Save Changes',
      'choose_birth_date': 'Please select a birth date',
      'select_date_hint': 'Select date',

      // Dashboard
      'welcome_to_app': 'Welcome to AquaTrack Pro',
      'not_logged_yet': 'Not logged yet today',
      'log_now': 'Log Now',
      'last_updated_today': 'Last updated: today',
      'no_data_yet': 'Not logged',
      'rest_day': 'Rest',

      // Reports
      'add_athlete_first': 'Add an athlete first',
      'no_data_enough': 'Not enough data',
      'days_7': '7D',
      'days_14': '14D',
      'days_30': '30D',
      'stress': 'Stress',

      // General
      'coming_soon': 'Coming Soon',
      'years_old': 'years old',
      'beats': 'bpm',

      // COPPA
      'consent_title': 'Parental Consent',
      'consent_text': 'I consent to the collection and storage of my child\'s health data for sports monitoring and analysis purposes. I understand that data will only be used for this purpose and will not be shared with third parties.',
      'consent_agree': 'I Agree',
      'consent_disagree': 'I Disagree',
      'parental_consent_required': 'Parental consent is required',
      'forgot_password_body': 'Enter your email and we\'ll send you a password reset link',
      'send_reset_link': 'Send Reset Link',
      'reset_email_sent': 'Password reset email sent',
      'and': 'and',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final lang = isArabic ? 'ar' : 'en';
    String? value = _localizedValues[lang]?[key];
    if (value == null && isArabic) {
      value = _localizedValues['en']?[key];
    }
    if (value == null) return key;
    if (params != null) {
      params.forEach((k, v) {
        value = value!.replaceAll('@$k', v);
      });
    }
    return value ?? key;
  }
}
